version: "2"
services:
  node:
    image: "node:12"
    user: "node"
    working_dir: /home/node/admin
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/admin
    ports:
    - "3000:3000"
    command: "npm run start"